<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Microsoft.Exchange.WebServices</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" Version="9.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.4" />
  </ItemGroup>
</Project>